
/**
 * @author juandavidpaz, juan camilo velez, jhonatan bellaiza, daniel alejandro cerquera
 */
package modelo;

public interface Constantes {

	/**
	 * Constantes para diferenciar al equipo que pertenece una ficha.
	 */
	public final static int UNO = 1;
	public final static int DOS = 2;
	public final static int TRES = 3;
	public final static int CUATRO = 4;
	
	/**
	 * Constantes para diferenciar el tipo de casillas.
	 */
	public static final int NORMAL = 1;
	public static final int SALIDA = 2;
	public static final int SEGURO = 3;
	public static final int CASA = 4;
	
	public final static Lamina[] lAMINAS= {
	new Lamina("./Archivos/imagenes/laminas/rusia/akinfeev.jpg",1),
	new Lamina("./Archivos/imagenes/laminas/rusia/dzagoev.jpg",2),
	new Lamina("./Archivos/imagenes/laminas/rusia/erokhin.jpg",3),
	new Lamina("./Archivos/imagenes/laminas/rusia/fernandes.jpg",4),
	new Lamina("./Archivos/imagenes/laminas/rusia/kokorin.jpg",5),
	new Lamina("./Archivos/imagenes/laminas/rusia/kudryashov.jpg",6),
	new Lamina("./Archivos/imagenes/laminas/rusia/miranchuk.jpg",7),
	new Lamina("./Archivos/imagenes/laminas/rusia/poloz.jpg",8),
	new Lamina("./Archivos/imagenes/laminas/rusia/samedov.jpg",9),
	new Lamina("./Archivos/imagenes/laminas/rusia/smolnikov.jpg",10),
	new Lamina("./Archivos/imagenes/laminas/rusia/vasin.jpg",11),
	
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-mayouf.jpg",12),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-beraik.jpg",13),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-dosari.jpg",14),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-harbi.jpg",15),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-jassim.jpg",16),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-moasher.jpg",17),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-sahlawi.jpg",18),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-shahrani.jpg",19),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-shamrani.jpg",20),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/al-shehri.jpg",21),
	new Lamina("./Archivos/imagenes/laminas/arabia saudita/hawsawi.jpg",22),
	
	new Lamina("./Archivos/imagenes/laminas/egipto/hadary.jpg",23),
	new Lamina("./Archivos/imagenes/laminas/egipto/el-said.jpg",24),
	new Lamina("./Archivos/imagenes/laminas/egipto/elmohamady.jpg",25),
	new Lamina("./Archivos/imagenes/laminas/egipto/elneny.jpg",26),
	new Lamina("./Archivos/imagenes/laminas/egipto/gabr.jpg",27),
	new Lamina("./Archivos/imagenes/laminas/egipto/hegazi.jpg",28),
	new Lamina("./Archivos/imagenes/laminas/egipto/kahraba.jpg",29),
	new Lamina("./Archivos/imagenes/laminas/egipto/rabia.jpg",30),
	new Lamina("./Archivos/imagenes/laminas/egipto/salah.jpg",31),
	new Lamina("./Archivos/imagenes/laminas/egipto/sobhi.jpg",32),
	new Lamina("./Archivos/imagenes/laminas/egipto/trezeguet.jpg",33),
	
	new Lamina("./Archivos/imagenes/laminas/uruguay/muslera.jpg",34),
	new Lamina("./Archivos/imagenes/laminas/uruguay/stuani.jpg",35),
	new Lamina("./Archivos/imagenes/laminas/uruguay/suarez.jpg",36),
	new Lamina("./Archivos/imagenes/laminas/uruguay/sanchez.jpg",37),
	new Lamina("./Archivos/imagenes/laminas/uruguay/pereira.jpg",38),
	new Lamina("./Archivos/imagenes/laminas/uruguay/godin.jpg",39),
	new Lamina("./Archivos/imagenes/laminas/uruguay/lodeiro.jpg",40),
	new Lamina("./Archivos/imagenes/laminas/uruguay/gimenez.jpg",41),
	new Lamina("./Archivos/imagenes/laminas/uruguay/cavani.jpg",42),
	new Lamina("./Archivos/imagenes/laminas/uruguay/caceres.jpg",43),
	new Lamina("./Archivos/imagenes/laminas/uruguay/cRodriguez.jpg",44),
	
	new Lamina("./Archivos/imagenes/laminas/portugal/patricio.jpg",45),
	new Lamina("./Archivos/imagenes/laminas/portugal/aSilva.jpg",46),
	new Lamina("./Archivos/imagenes/laminas/portugal/carvalho.jpg",47),
	new Lamina("./Archivos/imagenes/laminas/portugal/cristiano.jpg",48),
	new Lamina("./Archivos/imagenes/laminas/portugal/eliseu.jpg",49),
	new Lamina("./Archivos/imagenes/laminas/portugal/fonte.jpg",50),
	new Lamina("./Archivos/imagenes/laminas/portugal/guerreiro.jpg",51),
	new Lamina("./Archivos/imagenes/laminas/portugal/moutinho.jpg",52),
	new Lamina("./Archivos/imagenes/laminas/portugal/nani.jpg",53),
	new Lamina("./Archivos/imagenes/laminas/portugal/pepe.jpg",54),
	new Lamina("./Archivos/imagenes/laminas/portugal/silva.jpg",55),
	
	new Lamina("./Archivos/imagenes/laminas/espana/DeGea.jpg",56),
	new Lamina("./Archivos/imagenes/laminas/espana/alba.jpg",57),
	new Lamina("./Archivos/imagenes/laminas/espana/asensio.jpg",58),
	new Lamina("./Archivos/imagenes/laminas/espana/busquet.jpg",59),
	new Lamina("./Archivos/imagenes/laminas/espana/carvajal.jpg",60),
	new Lamina("./Archivos/imagenes/laminas/espana/costa.jpg",61),
	new Lamina("./Archivos/imagenes/laminas/espana/iniesta.jpg",62),
	new Lamina("./Archivos/imagenes/laminas/espana/isco.jpg",63),
	new Lamina("./Archivos/imagenes/laminas/espana/morata.jpg",64),
	new Lamina("./Archivos/imagenes/laminas/espana/ramos.jpg",65),
	new Lamina("./Archivos/imagenes/laminas/espana/vitolo.jpg",66),
	
	new Lamina("./Archivos/imagenes/laminas/marruecos/mohamedi.jpg",67),
	new Lamina("./Archivos/imagenes/laminas/marruecos/alioui.jpg",68),
	new Lamina("./Archivos/imagenes/laminas/marruecos/amrabat.jpg",69),
	new Lamina("./Archivos/imagenes/laminas/marruecos/bouhaddouz.jpg",70),
	new Lamina("./Archivos/imagenes/laminas/marruecos/chafik.jpg",71),
	new Lamina("./Archivos/imagenes/laminas/marruecos/en-nesyri.jpg",72),
	new Lamina("./Archivos/imagenes/laminas/marruecos/fajr.jpg",73),
	new Lamina("./Archivos/imagenes/laminas/marruecos/hakimi.jpg",74),
	new Lamina("./Archivos/imagenes/laminas/marruecos/mendyl.jpg",75),
	new Lamina("./Archivos/imagenes/laminas/marruecos/saiss.jpg",76),
	new Lamina("./Archivos/imagenes/laminas/marruecos/ziyech.jpg",77),
	
	new Lamina("./Archivos/imagenes/laminas/iran/beiranvand.jpg",78),
	new Lamina("./Archivos/imagenes/laminas/iran/amiri.jpg",79),
	new Lamina("./Archivos/imagenes/laminas/iran/ansarifard.jpg",80),
	new Lamina("./Archivos/imagenes/laminas/iran/azmoun.jpg",81),
	new Lamina("./Archivos/imagenes/laminas/iran/ebrahimi.jpg",82),
	new Lamina("./Archivos/imagenes/laminas/iran/ghafouri.jpg",83),
	new Lamina("./Archivos/imagenes/laminas/iran/ghoddos.jpg",84),
	new Lamina("./Archivos/imagenes/laminas/iran/ghoochannejhad.jpg",85),
	new Lamina("./Archivos/imagenes/laminas/iran/hajsafi.jpg",86),
	new Lamina("./Archivos/imagenes/laminas/iran/jakanbakhsh.jpg",87),
	new Lamina("./Archivos/imagenes/laminas/iran/rezaeian.jpg",88),
	
	new Lamina("./Archivos/imagenes/laminas/francia/lloris.jpg",89),
	new Lamina("./Archivos/imagenes/laminas/francia/dembele.jpg",90),
	new Lamina("./Archivos/imagenes/laminas/francia/griezmann.jpg",91),
	new Lamina("./Archivos/imagenes/laminas/francia/kurzawa.jpg",92),
	new Lamina("./Archivos/imagenes/laminas/francia/lemar.jpg",93),
	new Lamina("./Archivos/imagenes/laminas/francia/martial.jpg",94),
	new Lamina("./Archivos/imagenes/laminas/francia/mbappe.jpg",95),
	new Lamina("./Archivos/imagenes/laminas/francia/pogba.jpg",96),
	new Lamina("./Archivos/imagenes/laminas/francia/rabiot.jpg",97),
	new Lamina("./Archivos/imagenes/laminas/francia/umtiti.jpg",98),
	new Lamina("./Archivos/imagenes/laminas/francia/varane.jpg",99),
	
	new Lamina("./Archivos/imagenes/laminas/australia/ryan.jpg",100),
	new Lamina("./Archivos/imagenes/laminas/australia/behich.jpg",101),
	new Lamina("./Archivos/imagenes/laminas/australia/cahill.jpg",102),
	new Lamina("./Archivos/imagenes/laminas/australia/degenek.jpg",103),
	new Lamina("./Archivos/imagenes/laminas/australia/jedinak.jpg",104),
	new Lamina("./Archivos/imagenes/laminas/australia/juric.jpg",105),
	new Lamina("./Archivos/imagenes/laminas/australia/kruse.jpg",106),
	new Lamina("./Archivos/imagenes/laminas/australia/luongo.jpg",107),
	new Lamina("./Archivos/imagenes/laminas/australia/mcgowan.jpg",108),
	new Lamina("./Archivos/imagenes/laminas/australia/mooy.jpg",109),
	new Lamina("./Archivos/imagenes/laminas/australia/wright.jpg",110),
	
	new Lamina("./Archivos/imagenes/laminas/peru/gallese.jpg",111),
	new Lamina("./Archivos/imagenes/laminas/peru/araujo.jpg",112),
	new Lamina("./Archivos/imagenes/laminas/peru/corzo.jpg",113),
	new Lamina("./Archivos/imagenes/laminas/peru/cueva.jpg",114),
	new Lamina("./Archivos/imagenes/laminas/peru/farfan.jpg",115),
	new Lamina("./Archivos/imagenes/laminas/peru/guerrero.jpg",116),
	new Lamina("./Archivos/imagenes/laminas/peru/polo.jpg",117),
	new Lamina("./Archivos/imagenes/laminas/peru/rodriguez.jpg",118),
	new Lamina("./Archivos/imagenes/laminas/peru/ruidiaz.jpg",119),
	new Lamina("./Archivos/imagenes/laminas/peru/trauco.jpg",120),
	new Lamina("./Archivos/imagenes/laminas/peru/yotun.jpg",121),
	
	new Lamina("./Archivos/imagenes/laminas/dinamarca/schmeichel.jpg",122),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/bjelland.jpg",123),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/christensen.jpg",124),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/cornelius.jpg",125),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/eriksen.jpg",126),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/jorgensen.jpg",127),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/kjaer.jpg",128),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/poulsen.jpg",129),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/schone.jpg",130),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/sisto.jpg",131),
	new Lamina("./Archivos/imagenes/laminas/dinamarca/vestergaard.jpg",132),
	
	new Lamina("./Archivos/imagenes/laminas/argentina/romero.jpg",133),
	new Lamina("./Archivos/imagenes/laminas/argentina/aguero.jpg",134),
	new Lamina("./Archivos/imagenes/laminas/argentina/di maria.jpg",135),
	new Lamina("./Archivos/imagenes/laminas/argentina/dybala.jpg",136),
	new Lamina("./Archivos/imagenes/laminas/argentina/fazio.jpg",137),
	new Lamina("./Archivos/imagenes/laminas/argentina/higuain.jpg",138),
	new Lamina("./Archivos/imagenes/laminas/argentina/icardi.jpg",139),
	new Lamina("./Archivos/imagenes/laminas/argentina/masherano.jpg",140),
	new Lamina("./Archivos/imagenes/laminas/argentina/messi.jpg",141),
	new Lamina("./Archivos/imagenes/laminas/argentina/otamendi.jpg",142),
	new Lamina("./Archivos/imagenes/laminas/argentina/perez.jpg",143),
	
	new Lamina("./Archivos/imagenes/laminas/islandia/halldorsson.jpg",144),
	new Lamina("./Archivos/imagenes/laminas/islandia/bjarnason.jpg",145),
	new Lamina("./Archivos/imagenes/laminas/islandia/bodvarsson.jpg",146),
	new Lamina("./Archivos/imagenes/laminas/islandia/finnbogason.jpg",147),
	new Lamina("./Archivos/imagenes/laminas/islandia/gislason.jpg",148),
	new Lamina("./Archivos/imagenes/laminas/islandia/gunnarsson.jpg",149),
	new Lamina("./Archivos/imagenes/laminas/islandia/hallfredsson.jpg",150),
	new Lamina("./Archivos/imagenes/laminas/islandia/ingason.jpg",151),
	new Lamina("./Archivos/imagenes/laminas/islandia/sigurdarson.jpg",152),
	new Lamina("./Archivos/imagenes/laminas/islandia/sigurdsson.jpg",153),
	new Lamina("./Archivos/imagenes/laminas/islandia/skulason.jpg",154),
	
	new Lamina("./Archivos/imagenes/laminas/croacia/subasic.jpg",155),
	new Lamina("./Archivos/imagenes/laminas/croacia/kalinic.jpg",156),
	new Lamina("./Archivos/imagenes/laminas/croacia/kovacic.jpg",157),
	new Lamina("./Archivos/imagenes/laminas/croacia/kramaric.jpg",158),
	new Lamina("./Archivos/imagenes/laminas/croacia/mandzukic.jpg",159),
	new Lamina("./Archivos/imagenes/laminas/croacia/modric.jpg",160),
	new Lamina("./Archivos/imagenes/laminas/croacia/perisic.jpg",161),
	new Lamina("./Archivos/imagenes/laminas/croacia/pivaric.jpg",162),
	new Lamina("./Archivos/imagenes/laminas/croacia/rakitic.jpg",163),
	new Lamina("./Archivos/imagenes/laminas/croacia/strinic.jpg",164),
	new Lamina("./Archivos/imagenes/laminas/croacia/vida.jpg",165),
	
	new Lamina("./Archivos/imagenes/laminas/nigeria/ezenwa.jpg",166),
	new Lamina("./Archivos/imagenes/laminas/nigeria/aina.jpg",167),
	new Lamina("./Archivos/imagenes/laminas/nigeria/balogun.jpg",168),
	new Lamina("./Archivos/imagenes/laminas/nigeria/echijile.jpg",169),
	new Lamina("./Archivos/imagenes/laminas/nigeria/ighalo.jpg",170),
	new Lamina("./Archivos/imagenes/laminas/nigeria/iheanacho.jpg",171),
	new Lamina("./Archivos/imagenes/laminas/nigeria/iwobi.jpg",172),
	new Lamina("./Archivos/imagenes/laminas/nigeria/mikel.jpg",173),
	new Lamina("./Archivos/imagenes/laminas/nigeria/musa.jpg",174),
	new Lamina("./Archivos/imagenes/laminas/nigeria/ndidi.jpg",175),
	new Lamina("./Archivos/imagenes/laminas/nigeria/omeruo.jpg",176),
	
	new Lamina("./Archivos/imagenes/laminas/brasil/alisson.jpg",177),
	new Lamina("./Archivos/imagenes/laminas/brasil/alves.jpg",178),
	new Lamina("./Archivos/imagenes/laminas/brasil/casemiro.jpg",179),
	new Lamina("./Archivos/imagenes/laminas/brasil/coutinho.jpg",180),
	new Lamina("./Archivos/imagenes/laminas/brasil/firminho.jpg",181),
	new Lamina("./Archivos/imagenes/laminas/brasil/jesus.jpg",182),
	new Lamina("./Archivos/imagenes/laminas/brasil/marcelo.jpg",183),
	new Lamina("./Archivos/imagenes/laminas/brasil/marquinhos.jpg",184),
	new Lamina("./Archivos/imagenes/laminas/brasil/neymar.jpg",185),
	new Lamina("./Archivos/imagenes/laminas/brasil/paulinho.jpg",186),
	new Lamina("./Archivos/imagenes/laminas/brasil/silva.jpg",187),
	
	new Lamina("./Archivos/imagenes/laminas/suiza/sommer.jpg",188),
	new Lamina("./Archivos/imagenes/laminas/suiza/akanji.jpg",189),
	new Lamina("./Archivos/imagenes/laminas/suiza/behrami.jpg",190),
	new Lamina("./Archivos/imagenes/laminas/suiza/derdijok.jpg",191),
	new Lamina("./Archivos/imagenes/laminas/suiza/djorou.jpg",192),
	new Lamina("./Archivos/imagenes/laminas/suiza/embolo.jpg",193),
	new Lamina("./Archivos/imagenes/laminas/suiza/lichtsteiner.jpg",194),
	new Lamina("./Archivos/imagenes/laminas/suiza/mehmedi.jpg",195),
	new Lamina("./Archivos/imagenes/laminas/suiza/rodriguez.jpg",196),
	new Lamina("./Archivos/imagenes/laminas/suiza/shaqiri.jpg",197),
	new Lamina("./Archivos/imagenes/laminas/suiza/xhaka.jpg",198),
	
	new Lamina("./Archivos/imagenes/laminas/costa rica/navas.jpg",199),
	new Lamina("./Archivos/imagenes/laminas/costa rica/azofeifa.jpg",200),
	new Lamina("./Archivos/imagenes/laminas/costa rica/borges.jpg",201),
	new Lamina("./Archivos/imagenes/laminas/costa rica/calvo.jpg",202),
	new Lamina("./Archivos/imagenes/laminas/costa rica/guzman.jpg",203),
	new Lamina("./Archivos/imagenes/laminas/costa rica/matarrita.jpg",204),
	new Lamina("./Archivos/imagenes/laminas/costa rica/oviedo.jpg",205),
	new Lamina("./Archivos/imagenes/laminas/costa rica/urena.jpg",206),
	new Lamina("./Archivos/imagenes/laminas/costa rica/venegas.jpg",207),
	new Lamina("./Archivos/imagenes/laminas/costa rica/wallace.jpg",208),
	new Lamina("./Archivos/imagenes/laminas/costa rica/waston.jpg",209),
	
	new Lamina("./Archivos/imagenes/laminas/serbia/stojkovic.jpg",210),
	new Lamina("./Archivos/imagenes/laminas/serbia/gacinovic.jpg",211),
	new Lamina("./Archivos/imagenes/laminas/serbia/ivanovic.jpg",212),
	new Lamina("./Archivos/imagenes/laminas/serbia/kolarov.jpg",213),
	new Lamina("./Archivos/imagenes/laminas/serbia/kostic.jpg",214),
	new Lamina("./Archivos/imagenes/laminas/serbia/milivojevic.jpg",215),
	new Lamina("./Archivos/imagenes/laminas/serbia/mitrovic.jpg",216),
	new Lamina("./Archivos/imagenes/laminas/serbia/nastasic.jpg",217),
	new Lamina("./Archivos/imagenes/laminas/serbia/prijovic.jpg",218),
	new Lamina("./Archivos/imagenes/laminas/serbia/rukavina.jpg",219),
	new Lamina("./Archivos/imagenes/laminas/serbia/vukovic.jpg",220),
	
	new Lamina("./Archivos/imagenes/laminas/alemania/neuer.jpg",221),
	new Lamina("./Archivos/imagenes/laminas/alemania/boateng.jpg",222),
	new Lamina("./Archivos/imagenes/laminas/alemania/draxler.jpg",223),
	new Lamina("./Archivos/imagenes/laminas/alemania/gotze.jpg",224),
	new Lamina("./Archivos/imagenes/laminas/alemania/hummels.jpg",225),
	new Lamina("./Archivos/imagenes/laminas/alemania/khedira.jpg",226),
	new Lamina("./Archivos/imagenes/laminas/alemania/kroos.jpg",227),
	new Lamina("./Archivos/imagenes/laminas/alemania/muller.jpg",228),
	new Lamina("./Archivos/imagenes/laminas/alemania/ozil.jpg",229),
	new Lamina("./Archivos/imagenes/laminas/alemania/sane.jpg",230),
	new Lamina("./Archivos/imagenes/laminas/alemania/werner.jpg",231),
	
	new Lamina("./Archivos/imagenes/laminas/mexico/ochoa.jpg",232),
	new Lamina("./Archivos/imagenes/laminas/mexico/chicharito.jpg",233),
	new Lamina("./Archivos/imagenes/laminas/mexico/dos-santos.jpg",234),
	new Lamina("./Archivos/imagenes/laminas/mexico/gallardo.jpg",235),
	new Lamina("./Archivos/imagenes/laminas/mexico/gDosSantos.jpg",236),
	new Lamina("./Archivos/imagenes/laminas/mexico/herrera.jpg",237),
	new Lamina("./Archivos/imagenes/laminas/mexico/jimenez.jpg",238),
	new Lamina("./Archivos/imagenes/laminas/mexico/layun.jpg",239),
	new Lamina("./Archivos/imagenes/laminas/mexico/moreno.jpg",240),
	new Lamina("./Archivos/imagenes/laminas/mexico/reyes.jpg",241),
	new Lamina("./Archivos/imagenes/laminas/mexico/vela.jpg",242),
	
	new Lamina("./Archivos/imagenes/laminas/suecia/olsen.jpg",243),
	new Lamina("./Archivos/imagenes/laminas/suecia/berg.jpg",244),
	new Lamina("./Archivos/imagenes/laminas/suecia/durmaz.jpg",245),
	new Lamina("./Archivos/imagenes/laminas/suecia/forsberg.jpg",246),
	new Lamina("./Archivos/imagenes/laminas/suecia/granqist.jpg",247),
	new Lamina("./Archivos/imagenes/laminas/suecia/jansson.jpg",248),
	new Lamina("./Archivos/imagenes/laminas/suecia/larsson.jpg",249),
	new Lamina("./Archivos/imagenes/laminas/suecia/lindelof.jpg",250),
	new Lamina("./Archivos/imagenes/laminas/suecia/olsson.jpg",251),
	new Lamina("./Archivos/imagenes/laminas/suecia/svensson.jpg",252),
	new Lamina("./Archivos/imagenes/laminas/suecia/thelin.jpg",253),
	
	new Lamina("./Archivos/imagenes/laminas/corea/seunggyu.jpg",254),
	new Lamina("./Archivos/imagenes/laminas/corea/dongwon.jpg",255),
	new Lamina("./Archivos/imagenes/laminas/corea/heechan.jpg",256),
	new Lamina("./Archivos/imagenes/laminas/corea/jeongho.jpg",257),
	new Lamina("./Archivos/imagenes/laminas/corea/jinsu.jpg",258),
	new Lamina("./Archivos/imagenes/laminas/corea/kookyoung.jpg",259),
	new Lamina("./Archivos/imagenes/laminas/corea/shinwook.jpg",260),
	new Lamina("./Archivos/imagenes/laminas/corea/sungyueng.jpg",261),
	new Lamina("./Archivos/imagenes/laminas/corea/taehee.jpg",262),
	new Lamina("./Archivos/imagenes/laminas/corea/taehwi.jpg",263),
	new Lamina("./Archivos/imagenes/laminas/corea/younggwon.jpg",264),
	
	new Lamina("./Archivos/imagenes/laminas/belgica/courtois.jpg",265),
	new Lamina("./Archivos/imagenes/laminas/belgica/bruyne.jpg",266),
	new Lamina("./Archivos/imagenes/laminas/belgica/carrasco.jpg",267),
	new Lamina("./Archivos/imagenes/laminas/belgica/fellaini.jpg",268),
	new Lamina("./Archivos/imagenes/laminas/belgica/hazard.jpg",269),
	new Lamina("./Archivos/imagenes/laminas/belgica/kompany.jpg",270),
	new Lamina("./Archivos/imagenes/laminas/belgica/lukaku.jpg",271),
	new Lamina("./Archivos/imagenes/laminas/belgica/mertens.jpg",272),
	new Lamina("./Archivos/imagenes/laminas/belgica/meunier.jpg",273),
	new Lamina("./Archivos/imagenes/laminas/belgica/nainggolan.jpg",274),
	new Lamina("./Archivos/imagenes/laminas/belgica/vertonghen.jpg",275),
	
	new Lamina("./Archivos/imagenes/laminas/panama/calderon.jpg",276),
	new Lamina("./Archivos/imagenes/laminas/panama/arroyo.jpg",277),
	new Lamina("./Archivos/imagenes/laminas/panama/barcenas.jpg",278),
	new Lamina("./Archivos/imagenes/laminas/panama/davis.jpg",279),
	new Lamina("./Archivos/imagenes/laminas/panama/godoy.jpg",280),
	new Lamina("./Archivos/imagenes/laminas/panama/gTorres.jpg",281),
	new Lamina("./Archivos/imagenes/laminas/panama/machado.jpg",282),
	new Lamina("./Archivos/imagenes/laminas/panama/murillo.jpg",283),
	new Lamina("./Archivos/imagenes/laminas/panama/quintero.jpg",284),
	new Lamina("./Archivos/imagenes/laminas/panama/tejada.jpg",285),
	new Lamina("./Archivos/imagenes/laminas/panama/torres.jpg",286),
	
	new Lamina("./Archivos/imagenes/laminas/tunez/mathlouthi.jpg",287),
	new Lamina("./Archivos/imagenes/laminas/tunez/akaichi.jpg",288),
	new Lamina("./Archivos/imagenes/laminas/tunez/badri.jpg",289),
	new Lamina("./Archivos/imagenes/laminas/tunez/chaalali.jpg",290),
	new Lamina("./Archivos/imagenes/laminas/tunez/khazri.jpg",291),
	new Lamina("./Archivos/imagenes/laminas/tunez/maaloul.jpg",292),
	new Lamina("./Archivos/imagenes/laminas/tunez/meriah.jpg",293),
	new Lamina("./Archivos/imagenes/laminas/tunez/naguez.jpg",294),
	new Lamina("./Archivos/imagenes/laminas/tunez/sliti.jpg",295),
	new Lamina("./Archivos/imagenes/laminas/tunez/touzghar.jpg",296),
	new Lamina("./Archivos/imagenes/laminas/tunez/youssef.jpg",297),
	
	new Lamina("./Archivos/imagenes/laminas/inglaterra/hart.jpg",298),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/alli.jpg",299),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/bertrand.jpg",300),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/cahill.jpg",301),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/henderson.jpg",302),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/kane.jpg",303),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/lingard.jpg",304),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/rose.jpg",305),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/sterling.jpg",306),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/vardy.jpg",307),
	new Lamina("./Archivos/imagenes/laminas/inglaterra/walker.jpg",308),
	
	new Lamina("./Archivos/imagenes/laminas/polonia/szczesny.jpg",309),
	new Lamina("./Archivos/imagenes/laminas/polonia/artur.jpg",310),
	new Lamina("./Archivos/imagenes/laminas/polonia/bartosz.jpg",311),
	new Lamina("./Archivos/imagenes/laminas/polonia/cionek.jpg",312),
	new Lamina("./Archivos/imagenes/laminas/polonia/glik.jpg",313),
	new Lamina("./Archivos/imagenes/laminas/polonia/grosicki.jpg",314),
	new Lamina("./Archivos/imagenes/laminas/polonia/krychowiak.jpg",315),
	new Lamina("./Archivos/imagenes/laminas/polonia/linetty.jpg",316),
	new Lamina("./Archivos/imagenes/laminas/polonia/rybus.jpg",317),
	new Lamina("./Archivos/imagenes/laminas/polonia/piszczek.jpg",318),
	new Lamina("./Archivos/imagenes/laminas/polonia/teodorczyk.jpg",319),
	
	new Lamina("./Archivos/imagenes/laminas/senegal/diaye.jpg",320),
	new Lamina("./Archivos/imagenes/laminas/senegal/balde.jpg",321),
	new Lamina("./Archivos/imagenes/laminas/senegal/gassama.jpg",322),
	new Lamina("./Archivos/imagenes/laminas/senegal/konate.jpg",323),
	new Lamina("./Archivos/imagenes/laminas/senegal/koulibaly.jpg",324),
	new Lamina("./Archivos/imagenes/laminas/senegal/kouyate.jpg",325),
	new Lamina("./Archivos/imagenes/laminas/senegal/mane.jpg",326),
	new Lamina("./Archivos/imagenes/laminas/senegal/mbodj.jpg",327),
	new Lamina("./Archivos/imagenes/laminas/senegal/ndoye.jpg",328),
	new Lamina("./Archivos/imagenes/laminas/senegal/niang.jpg",329),
	new Lamina("./Archivos/imagenes/laminas/senegal/sane.jpg",330),
	
	new Lamina("./Archivos/imagenes/laminas/colombia/ospina.jpg",331),
	new Lamina("./Archivos/imagenes/laminas/colombia/arias.jpg",332),
	new Lamina("./Archivos/imagenes/laminas/colombia/bacca.jpg",333),
	new Lamina("./Archivos/imagenes/laminas/colombia/barrios.jpg",334),
	new Lamina("./Archivos/imagenes/laminas/colombia/cSanchez.jpg",335),
	new Lamina("./Archivos/imagenes/laminas/colombia/cZapata.jpg",336),
	new Lamina("./Archivos/imagenes/laminas/colombia/dSanchez.jpg",337),
	new Lamina("./Archivos/imagenes/laminas/colombia/dZapata.jpg",338),
	new Lamina("./Archivos/imagenes/laminas/colombia/falcao.jpg",339),
	new Lamina("./Archivos/imagenes/laminas/colombia/mina.jpg",340),
	new Lamina("./Archivos/imagenes/laminas/colombia/rodriguez.jpg",341),
	
	new Lamina("./Archivos/imagenes/laminas/japon/nishikawa.jpg",342),
	new Lamina("./Archivos/imagenes/laminas/japon/h. sakai.jpg",343),
	new Lamina("./Archivos/imagenes/laminas/japon/hasebe.jpg",344),
	new Lamina("./Archivos/imagenes/laminas/japon/honda.jpg",345),
	new Lamina("./Archivos/imagenes/laminas/japon/kagawa.jpg",346),
	new Lamina("./Archivos/imagenes/laminas/japon/kubo.jpg",347),
	new Lamina("./Archivos/imagenes/laminas/japon/morishige.jpg",348),
	new Lamina("./Archivos/imagenes/laminas/japon/nagatomo.jpg",349),
	new Lamina("./Archivos/imagenes/laminas/japon/okazaki.jpg",350),
	new Lamina("./Archivos/imagenes/laminas/japon/osako.jpg",351),
	new Lamina("./Archivos/imagenes/laminas/japon/sakai.jpg",352),
	
	
	
	};

}
